In [151]:
import tensorflow as tf
import keras
import numpy as np
import pandas as pd
from pca import *
from main import getLineidxs
from readply import expandIndices, getIndices, getNearestDist

In [152]:
def calcSpecificModel(eigenValues, mean, eigenVectors):
    U_k = eigenVectors[:, 0:30]
    print('eigenValues: ', eigenValues)
    eigenValues = eigenValues.transpose()
    x_redBase = copyList(eigenValues)
    x_red = copyList(eigenValues)
    print('eigenvalues shape:' , np.array(eigenValues).shape)
    basePCAmodel = (np.dot(U_k, x_redBase) + mean).real
    adjustedModel = (np.dot(U_k, x_red) + mean).real
    cutoff = 5
    indices = rp.getIndices('breast_indices/leftBreastIdxLargeArea.txt') + rp.getIndices('breast_indices/rightBreastIdxLargeArea.txt')
    outline = rp.getIndices('breast_indices/leftBreastIdxLargeAreaOutline.txt') + rp.getIndices('breast_indices/rightBreastIdxLargeAreaOutline.txt')
    indices = list(set(indices))
    dists = []
    for i in indices:
        dists.append(rp.getNearestDist(outline, adjustedModel, adjustedModel[i*3], adjustedModel[i*3+1], adjustedModel[i*3+2]))

    indices_exp = rp.expandIndices(indices)
    for i in range(len(indices_exp)):
        dist = dists[int(i/3)]
        if dist > cutoff:
            basePCAmodel[indices_exp[i]] = adjustedModel[indices_exp[i]]
        else:
            basePCAmodel[indices_exp[i]] = (dist/cutoff) * adjustedModel[indices_exp[i]] + (1-(dist/cutoff)) * basePCAmodel[indices_exp[i]]
    return basePCAmodel

def copyList(l):
    r = []
    for i in range(len(l)):
        r.append(l[i])
    return r

In [153]:
df_lines = pd.read_csv('lines.txt', sep=' ', header=None)
df_params = pd.read_csv('params.txt', sep=' ', header=None)
eigenVectors = read_matrix_from_hdf5('eigenVectors.h5')
mean = read_matrix_from_hdf5('mean.h5')
leftLineIdxs, rightLineIdxs = getLineidxs()

In [154]:
eigenValuesAugmentation_fit = [37.47394805, -49.07828283,  -0.6562043,  -24.62020633, -27.13628352, 6.57057748, -11.42703975, -18.79096601, -10.54424185, 3.44637848, -12.89579981, -7.87242574, -13.9092693, 2.27681137, -7.3060829, -7.73122333, -4.43121648, 5.80548907, 10.15422231, 14.24570948, -17.25150115, 0.97727416, -3.08962112, 5.8461985, 6.87403008, -3.17929581, 1.36895233, -0.74191196, -0.60536829, 5.94243889]
for i in range(30):
    df_lines[114+i] = [eigenValuesAugmentation_fit[i]] * len(df_lines)
train_data = df_lines.sample(frac=0.8,random_state=200)
test_data = df_lines.drop(train_data.index)
x_train = train_data
y_train = train_data.iloc[:, 0:114]
x_test = test_data
y_test = test_data.iloc[:, 0:114]

In [155]:
model = keras.Sequential([
    keras.layers.Dense(114, activation=tf.nn.relu, input_shape=(144,)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(64, activation=tf.nn.relu),
    keras.layers.Dense(32, activation=tf.nn.relu),
    keras.layers.Dense(30, activation=tf.nn.relu),
])

class CustomLoss(keras.losses.Loss):
    def __init__(self):
        super().__init__()
        
    def call(self, y_true, y_pred):
        y_true = y_true.numpy()[0]
        y_pred = y_pred.numpy()[0]
        print('y_true: ', len(y_true))
        print('y_pred: ', len(y_pred))
        model = calcSpecificModel(y_pred, mean, eigenVectors)
        idxs = expandIndices(rightLineIdxs)
        sums = 0
        for i in range(0,len(idxs),3):
                sums += np.sqrt((model[idxs[i]] - y_true[i])**2 + (model[idxs[i+1]] - y_true[i+1])**2 + (model[idxs[i+2]] - y_true[i+2])**2)
        print('sums: ', sums)
        return tf.constant(sums, dtype=tf.float32)
    
loss_fn = CustomLoss()
model.compile(optimizer='adam', loss=loss_fn, run_eagerly=True)

In [156]:
model.fit(x_train, y_train, epochs=10, batch_size=1)

Epoch 1/10
y_true:  114
y_pred:  30
eigenValues:  [0.         0.         2.7692885  2.6379542  0.         0.
 5.7611547  0.         2.4482896  0.         2.7288687  2.6301765
 7.144993   2.163571   2.2425163  0.10416281 0.         1.8082294
 2.5232878  2.319271   0.         0.         3.0324333  0.
 0.43400693 0.         8.394964   0.         0.         1.9299822 ]
eigenvalues shape: (30,)
sums:  56.4375013253338


ValueError: No gradients provided for any variable: (['dense_150/kernel:0', 'dense_150/bias:0', 'dense_151/kernel:0', 'dense_151/bias:0', 'dense_152/kernel:0', 'dense_152/bias:0', 'dense_153/kernel:0', 'dense_153/bias:0', 'dense_154/kernel:0', 'dense_154/bias:0', 'dense_155/kernel:0', 'dense_155/bias:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'dense_150/kernel:0' shape=(144, 114) dtype=float32, numpy=
array([[-0.0491861 , -0.09003512,  0.02177499, ..., -0.00919415,
        -0.0322129 , -0.1002748 ],
       [-0.08161794, -0.09800388,  0.10288084, ...,  0.13848191,
         0.02446996,  0.08145641],
       [-0.04487093, -0.02741075,  0.05417484, ...,  0.08360934,
        -0.11829676,  0.01522577],
       ...,
       [-0.08199291,  0.0572775 , -0.12745407, ..., -0.0317951 ,
         0.02575523,  0.02260385],
       [ 0.08542813,  0.0931437 , -0.05722107, ...,  0.04870391,
        -0.09060395,  0.1095778 ],
       [-0.0451086 , -0.02803287,  0.12121722, ...,  0.00358029,
        -0.01026848, -0.05045231]], dtype=float32)>), (None, <tf.Variable 'dense_150/bias:0' shape=(114,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>), (None, <tf.Variable 'dense_151/kernel:0' shape=(114, 128) dtype=float32, numpy=
array([[ 0.09172826,  0.05937432, -0.11514961, ...,  0.07492508,
        -0.06086711,  0.06488293],
       [ 0.00066009, -0.04867932,  0.09864578, ...,  0.02989845,
         0.12333885,  0.12698802],
       [ 0.01234899, -0.10772978,  0.04677343, ...,  0.1279192 ,
         0.04330477, -0.10807632],
       ...,
       [-0.02354985, -0.00570175, -0.08847836, ...,  0.04380779,
        -0.05650876,  0.04566045],
       [-0.02954225, -0.10541769, -0.05684792, ...,  0.13664258,
        -0.00603662,  0.00407569],
       [-0.15678553, -0.11955942,  0.1470378 , ..., -0.06265407,
         0.06888621,  0.1382685 ]], dtype=float32)>), (None, <tf.Variable 'dense_151/bias:0' shape=(128,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>), (None, <tf.Variable 'dense_152/kernel:0' shape=(128, 128) dtype=float32, numpy=
array([[ 0.02389134,  0.12740867,  0.03584649, ...,  0.04075198,
        -0.06829564, -0.03321391],
       [-0.04744192,  0.04666731,  0.0120461 , ..., -0.01424403,
         0.12499587,  0.03495121],
       [-0.06831696, -0.13711338,  0.00200641, ..., -0.10097434,
        -0.10993285,  0.03699224],
       ...,
       [-0.0050451 , -0.0418015 ,  0.11387654, ...,  0.11582904,
         0.05115353, -0.1161914 ],
       [ 0.12155657, -0.05977838, -0.08258983, ...,  0.05024722,
        -0.07459219,  0.04669264],
       [-0.11280666,  0.12631576,  0.07516083, ..., -0.07710779,
         0.07936861, -0.0309248 ]], dtype=float32)>), (None, <tf.Variable 'dense_152/bias:0' shape=(128,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>), (None, <tf.Variable 'dense_153/kernel:0' shape=(128, 64) dtype=float32, numpy=
array([[ 0.03873838, -0.13390082,  0.12930451, ..., -0.08487334,
        -0.05872717,  0.08347811],
       [-0.03969714,  0.10714255,  0.05950065, ..., -0.06321155,
         0.04208194, -0.03861861],
       [-0.06211282,  0.06884557,  0.10944457, ..., -0.07143672,
         0.01784451,  0.06042656],
       ...,
       [ 0.10185136,  0.01207697,  0.0643335 , ..., -0.11143083,
         0.0058493 , -0.03731909],
       [ 0.09069137,  0.06278983, -0.0071532 , ..., -0.04096586,
        -0.11209705, -0.01694569],
       [ 0.03577892, -0.02865016,  0.04726444, ..., -0.10402487,
         0.13037331, -0.00401993]], dtype=float32)>), (None, <tf.Variable 'dense_153/bias:0' shape=(64,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>), (None, <tf.Variable 'dense_154/kernel:0' shape=(64, 32) dtype=float32, numpy=
array([[-0.15330976, -0.12162721,  0.1914947 , ..., -0.08201981,
        -0.14478582,  0.15241545],
       [-0.18637478, -0.1359008 , -0.14020222, ...,  0.20513606,
        -0.1777361 ,  0.19145864],
       [ 0.1098069 ,  0.1590445 , -0.18211544, ...,  0.13362741,
         0.00131136, -0.23889184],
       ...,
       [ 0.20751059,  0.04067391, -0.1340195 , ...,  0.21802986,
         0.08525032,  0.05073971],
       [-0.12842202,  0.09808254, -0.02450341, ...,  0.24423313,
        -0.03769851,  0.00784248],
       [-0.1626364 , -0.10518295,  0.06444657, ...,  0.22666574,
         0.16405994,  0.1171574 ]], dtype=float32)>), (None, <tf.Variable 'dense_154/bias:0' shape=(32,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>), (None, <tf.Variable 'dense_155/kernel:0' shape=(32, 30) dtype=float32, numpy=
array([[-0.0016897 ,  0.29554594, -0.30434257, -0.03100684, -0.1685569 ,
        -0.07599474,  0.26407123,  0.15998441,  0.26615942,  0.24427062,
        -0.00734743,  0.19342011,  0.11924681, -0.0310227 , -0.10356557,
        -0.05441162, -0.0938762 , -0.03378868,  0.01042062, -0.2908194 ,
         0.08804107, -0.02014187, -0.06894977,  0.01558283,  0.01460031,
        -0.10104451, -0.08837815,  0.11018646,  0.10651755, -0.25139067],
       [-0.03621534,  0.13283005,  0.25829476, -0.28944618,  0.12749442,
        -0.24633932, -0.11746016,  0.1232017 ,  0.23674762,  0.04598451,
         0.30525327,  0.01367202, -0.07102293, -0.10452257, -0.13305114,
         0.05857182,  0.11283812,  0.12344024,  0.29880208,  0.10929835,
        -0.27048662, -0.24356475, -0.17375344,  0.12313828, -0.19187453,
        -0.02400532,  0.05053705,  0.01702413,  0.00063562, -0.14688195],
       [-0.22164802, -0.03609627,  0.23323959, -0.16924615,  0.29103398,
        -0.2911859 , -0.19429947, -0.0569441 , -0.18176557, -0.20039925,
        -0.07921152,  0.09737524, -0.25562426, -0.05719629,  0.12564564,
        -0.2057195 ,  0.22065419,  0.0379841 , -0.09853798, -0.12552126,
         0.0999133 , -0.24933359, -0.01425675,  0.23759538, -0.05006105,
        -0.0017342 ,  0.06913906,  0.01633614, -0.1884303 ,  0.02237964],
       [-0.03183109, -0.26938498,  0.19754815, -0.12013283, -0.06084687,
        -0.13240914, -0.2284038 ,  0.10230848, -0.0837415 , -0.23482695,
         0.2381494 ,  0.29282272, -0.12813348,  0.02981237,  0.01885742,
        -0.09099519, -0.04122844,  0.04308963,  0.08006045, -0.09168741,
        -0.02280772,  0.16741002, -0.01545689,  0.30208808,  0.23095286,
        -0.0879373 ,  0.19373989,  0.00613064, -0.06208228, -0.13264196],
       [-0.17363484, -0.0854301 ,  0.21416944, -0.28886276, -0.23293336,
        -0.27347204, -0.13079575,  0.06765175, -0.0794901 ,  0.04771873,
         0.07524669, -0.2644906 ,  0.0632675 ,  0.03283471, -0.02666056,
        -0.0898415 ,  0.12876132,  0.2301647 , -0.20203348,  0.14381737,
         0.30321336,  0.02631316,  0.10201174, -0.2471511 ,  0.1708743 ,
        -0.28960127, -0.03992063, -0.21423094, -0.18863708,  0.24749607],
       [ 0.08928666, -0.07821698,  0.06605482, -0.28820875,  0.23162872,
         0.06324056, -0.04440889, -0.06188804,  0.22724599, -0.06970161,
        -0.01642752,  0.25489974, -0.01560909,  0.05485627, -0.10804418,
         0.07481584, -0.06901801,  0.2829998 , -0.02881908, -0.04553393,
         0.293755  , -0.04901037,  0.19241685, -0.24998197, -0.16843452,
        -0.04074118, -0.1667687 ,  0.24583822,  0.1995557 ,  0.30690992],
       [-0.11421299, -0.13729915,  0.26121616,  0.23286343, -0.20580977,
        -0.19455068,  0.16129676, -0.24424925,  0.1913088 , -0.10718782,
        -0.2472206 ,  0.24756414,  0.05664298,  0.22737175,  0.2282629 ,
         0.02162904, -0.245087  ,  0.30892015,  0.30798882,  0.22597677,
         0.24934798, -0.217649  , -0.1889172 , -0.10264729, -0.15474552,
         0.22061324,  0.0272938 , -0.09814289, -0.24609227,  0.24944556],
       [ 0.03085375, -0.13739905, -0.09754391,  0.10002345, -0.2088319 ,
         0.1480498 ,  0.23432505, -0.2210052 ,  0.27503264,  0.2723503 ,
         0.21020126, -0.08982429,  0.1771422 ,  0.04239193,  0.02116784,
        -0.02237472, -0.04516289,  0.26924413,  0.28925002, -0.18035096,
        -0.24650235,  0.05430451,  0.29954636, -0.17298847,  0.18065631,
         0.14128453,  0.29074544, -0.19856624,  0.07015309, -0.13407889],
       [ 0.00170225, -0.00753596,  0.2607208 , -0.00330701,  0.0893164 ,
         0.18403381,  0.12862054, -0.2024299 ,  0.14931238, -0.1876128 ,
         0.05598119,  0.29409796, -0.26786646,  0.02509591,  0.21051508,
         0.29125208, -0.00138807, -0.08624803, -0.3048638 , -0.02166376,
        -0.24998902,  0.12229943,  0.25732613, -0.28626806, -0.10153151,
        -0.07253782,  0.24600989, -0.15709956, -0.14826971, -0.24322248],
       [ 0.02134126,  0.20994657,  0.00770187, -0.07838899,  0.11619946,
        -0.04827446,  0.20144701,  0.2766127 , -0.30425394,  0.02076498,
        -0.11903343, -0.09977022,  0.0244137 , -0.05364203, -0.13040851,
        -0.30270115,  0.2738846 , -0.27221578,  0.1037797 ,  0.14456055,
         0.26836497,  0.2603913 ,  0.10578975, -0.25646883,  0.16420639,
         0.2398082 , -0.30098903,  0.30132586, -0.17875493, -0.06506452],
       [-0.1395957 ,  0.21789598, -0.19115207,  0.0103991 , -0.0528132 ,
        -0.27884465,  0.00503656, -0.27311373,  0.1815122 , -0.19147646,
        -0.26103204,  0.05464956,  0.10103694,  0.18325979, -0.06468278,
         0.01916656, -0.25293848, -0.21475197,  0.2676487 ,  0.09188795,
         0.11562434, -0.11225057, -0.1958984 ,  0.14346582, -0.09730434,
        -0.1084294 ,  0.05078286, -0.08649339, -0.08468559,  0.23915172],
       [ 0.0581871 ,  0.09635743,  0.3049752 , -0.083519  ,  0.27502126,
         0.13686207,  0.08706313, -0.15266153,  0.03901401,  0.00768942,
        -0.30538315, -0.18075933,  0.28026557,  0.27999043, -0.2861694 ,
         0.13706529,  0.09556189, -0.00449589,  0.20743698, -0.10477118,
         0.15214115, -0.11355519, -0.24488555,  0.14055943,  0.18554372,
        -0.27117497, -0.04314283, -0.2064152 , -0.1420696 ,  0.1793175 ],
       [ 0.17184174, -0.02840865, -0.05232534, -0.22989327,  0.10948342,
         0.09235522, -0.14164536,  0.0527558 , -0.14628215,  0.08098993,
         0.28535736,  0.09515864,  0.19414425, -0.28559023,  0.02470452,
         0.13446316, -0.19648552,  0.04209095, -0.20450604,  0.15602499,
         0.16572315, -0.01870337, -0.1321078 ,  0.08763558, -0.1648716 ,
         0.00794026, -0.11367504,  0.05207998,  0.11694869,  0.13364628],
       [-0.13831785, -0.10380967,  0.11032626, -0.20656925, -0.03239423,
         0.13662288,  0.28284913, -0.05367699, -0.18616904,  0.00777635,
         0.20033169, -0.21650642,  0.177378  , -0.15003775, -0.30836874,
         0.29744118,  0.13795316, -0.30993822, -0.14319302,  0.12522474,
        -0.01723114,  0.29491723,  0.02219903,  0.05209228, -0.06078538,
        -0.20983705,  0.27261132, -0.28837734,  0.24185401, -0.1928187 ],
       [ 0.10607204, -0.0313836 ,  0.16162437,  0.04216513,  0.00284785,
        -0.29342657,  0.30155778,  0.27590597,  0.0067718 , -0.20528376,
         0.3047948 ,  0.21245658,  0.23962146,  0.10784206,  0.08410159,
         0.12442088, -0.15008818,  0.08836132, -0.24508396, -0.29457885,
         0.08080968,  0.22660142,  0.15753835, -0.19326133,  0.13107634,
         0.04875398, -0.09729291,  0.1495995 ,  0.0121595 ,  0.27132785],
       [ 0.08853123,  0.04854786, -0.03155917, -0.01483023, -0.2563716 ,
        -0.02235818,  0.1675094 ,  0.26814562, -0.12236382, -0.30378333,
        -0.10272643,  0.25067562,  0.12308371,  0.28331524, -0.14586866,
        -0.24685138, -0.14849149, -0.12188922,  0.22551173,  0.23693919,
         0.02836072,  0.01487058,  0.01955402,  0.1180461 , -0.10388909,
        -0.30039287, -0.12831503, -0.1990964 ,  0.0553267 , -0.13999644],
       [ 0.30655432, -0.20902757, -0.01295152,  0.13116527, -0.09982163,
        -0.29725176, -0.02198088, -0.23710008,  0.20495814, -0.17547363,
         0.15763342,  0.10582194,  0.21324086,  0.14697963, -0.01030678,
         0.26801473,  0.05971229, -0.01030344,  0.04470658, -0.04649857,
        -0.2525847 , -0.22718069,  0.27538306, -0.20685005, -0.2574247 ,
         0.03621444,  0.22989172, -0.16637798, -0.22130944,  0.11867097],
       [ 0.06846353, -0.23443246, -0.10646157, -0.01540726,  0.07294962,
         0.23434162,  0.17525247, -0.22440842,  0.02276781, -0.02846277,
        -0.21449038, -0.07591227, -0.18843949,  0.10850519, -0.04254287,
         0.21724164, -0.03614643,  0.07956398,  0.01377472, -0.09044307,
         0.23885632, -0.2940094 ,  0.30142432,  0.03381976,  0.20565534,
        -0.23103762, -0.19338906,  0.2749409 , -0.00277916, -0.18458591],
       [-0.18758091,  0.17249012, -0.1727659 , -0.2878331 , -0.22945708,
         0.29505628,  0.05672544, -0.30675408, -0.13623868, -0.20468345,
         0.27074522, -0.03601781,  0.10962322, -0.11588669, -0.09800977,
         0.17613491, -0.25917724, -0.04059654,  0.12311241, -0.2969203 ,
        -0.06504984, -0.17494303, -0.17357618,  0.14576817,  0.1565232 ,
        -0.10579242,  0.04492369,  0.07191309, -0.07879847,  0.12482452],
       [ 0.22172129,  0.28612542,  0.01684117,  0.22320199,  0.17086339,
         0.23604965,  0.1453442 , -0.30346936,  0.22093022,  0.1293287 ,
        -0.2917046 ,  0.1447669 ,  0.20879453, -0.27238807,  0.10998243,
         0.0858039 , -0.13268764, -0.06373408,  0.290367  ,  0.29574144,
        -0.24430749,  0.13397357,  0.24562585, -0.1705536 , -0.00601447,
        -0.26358604, -0.07123795, -0.19842124, -0.0331282 ,  0.23215902],
       [ 0.04710832, -0.25440508, -0.20208746, -0.12811315,  0.28282428,
        -0.10395585, -0.1461456 , -0.0326944 , -0.06914431, -0.18834418,
         0.09714088,  0.1682072 , -0.07465608,  0.11973038, -0.15601039,
        -0.13947733,  0.1470877 , -0.0617394 ,  0.13183632, -0.16980737,
         0.09642479,  0.29816407,  0.11118454, -0.16802044,  0.24231225,
         0.13154417, -0.15237057,  0.25012988,  0.21454638,  0.23159897],
       [ 0.23786104,  0.30928427,  0.00712484,  0.0517101 , -0.05334842,
        -0.16897729,  0.01509523, -0.05437082,  0.00171715, -0.236114  ,
         0.04288191,  0.0840418 ,  0.0565111 ,  0.08368647,  0.23290163,
        -0.23571654,  0.0120064 , -0.0029186 , -0.16919668,  0.11697888,
        -0.00366727,  0.1085245 ,  0.03394985, -0.26194996,  0.13257861,
        -0.1666306 , -0.20111704,  0.14306554, -0.07514441,  0.11873645],
       [-0.19977674, -0.05368054, -0.28205624, -0.11224546,  0.13317093,
        -0.0788544 , -0.30686155, -0.2646304 , -0.17588261, -0.11025997,
         0.18602064, -0.173687  , -0.30179465, -0.3080866 , -0.18799366,
        -0.23604214, -0.19809854,  0.09595558, -0.13227482, -0.06459838,
        -0.07568502,  0.16922814,  0.2639178 , -0.07906829,  0.08683538,
        -0.12363566, -0.08591197, -0.1735695 ,  0.03417066,  0.23459971],
       [ 0.11179709, -0.13543655, -0.28062955, -0.2660136 , -0.18760946,
         0.22217351, -0.14998671,  0.2409684 ,  0.18460363, -0.2179565 ,
        -0.15258463,  0.18978387, -0.23817286,  0.1956535 , -0.07883348,
         0.3029545 , -0.07314549, -0.1199397 ,  0.28539723, -0.20579834,
         0.1699808 , -0.04352143,  0.11443067, -0.03222418,  0.06412059,
         0.02464771,  0.22260821,  0.19637138,  0.17986715,  0.16052756],
       [ 0.04599637, -0.07455869, -0.04672575, -0.24270484, -0.22524534,
         0.19159085, -0.02466312,  0.29818892, -0.25488207,  0.05628023,
        -0.18393153,  0.00410479,  0.21328968, -0.0403735 ,  0.00949395,
         0.07116327, -0.29469094,  0.26050377, -0.03547543,  0.1473374 ,
        -0.02348095, -0.23534547,  0.11900452,  0.25745392, -0.09020433,
         0.17571527, -0.30186376, -0.02335486, -0.17827208, -0.14877029],
       [-0.21139362, -0.26281846,  0.13464999,  0.03287736, -0.2650938 ,
        -0.23049751,  0.16334373, -0.2028069 ,  0.17718798,  0.04196027,
        -0.26620013, -0.2599575 , -0.14446406, -0.21301176,  0.04660085,
        -0.2768731 ,  0.02108783,  0.2878865 ,  0.10375464, -0.00107974,
        -0.03958005,  0.17069525, -0.06008047,  0.00312361, -0.28723907,
        -0.29300767,  0.11546332, -0.07022859, -0.18443297, -0.18188417],
       [-0.19456863,  0.16989058, -0.13126977,  0.06709424, -0.10549107,
        -0.03501239,  0.05530787, -0.08723344, -0.28133178, -0.1687464 ,
         0.17033398,  0.09616324,  0.26176262,  0.19314235,  0.24007142,
        -0.2623836 ,  0.288895  , -0.14464828, -0.20668125, -0.0373604 ,
        -0.30218774, -0.268086  , -0.03988838,  0.0284625 ,  0.27064002,
         0.30891067,  0.15789923,  0.19456935, -0.2691664 ,  0.1488733 ],
       [ 0.07129535, -0.15969405, -0.09704007,  0.23391646,  0.12976956,
         0.19735378,  0.13765901, -0.12395622,  0.17725605,  0.29682928,
         0.23381418, -0.12270679,  0.25745952, -0.19083855,  0.0852862 ,
        -0.19350617, -0.1993663 , -0.025922  , -0.04523778,  0.01458785,
         0.18059349,  0.033571  ,  0.05746239, -0.01963621,  0.09317049,
         0.21927458, -0.16150703,  0.1639379 ,  0.23087543,  0.2755137 ],
       [ 0.08799684,  0.27444357,  0.06888115, -0.18094468,  0.07987583,
         0.15044093,  0.01305494, -0.1236608 ,  0.14582911, -0.2524612 ,
        -0.1654841 , -0.15673591, -0.19140282, -0.23640133,  0.03142026,
         0.03124425, -0.13497478,  0.21615142, -0.2693887 ,  0.02033362,
         0.26925474, -0.06617831, -0.05189997,  0.23936439, -0.18018112,
         0.01510575,  0.00941199,  0.29653692,  0.28365916, -0.28965667],
       [-0.11779356,  0.17689005,  0.28253508,  0.24007082, -0.29023853,
         0.1249997 , -0.08640192, -0.18954074, -0.15791118,  0.27281195,
        -0.2528043 , -0.09578715,  0.17438522, -0.18117712, -0.13556531,
         0.15115488, -0.1541495 , -0.24711528,  0.18202028, -0.11808489,
        -0.20910567, -0.18442541,  0.25556135, -0.09285259,  0.11425135,
        -0.24643908,  0.21106178, -0.2914063 , -0.15162963, -0.0497826 ],
       [ 0.2747848 , -0.30812946, -0.15883303,  0.18696791,  0.22500777,
         0.05604473, -0.22522435,  0.08650279,  0.23190361, -0.198788  ,
         0.0784831 , -0.05720282, -0.01518452,  0.18713033, -0.00109348,
        -0.23416248, -0.20766842,  0.27750754,  0.0489485 ,  0.17598245,
         0.11493665, -0.22962648,  0.16866592,  0.00413644, -0.02025834,
        -0.1502208 ,  0.02354673,  0.14877999, -0.10452688, -0.01979056],
       [-0.2940008 , -0.30252498,  0.23434454,  0.0294418 ,  0.29833615,
        -0.18477571,  0.04112396, -0.21993294, -0.2852564 , -0.2806991 ,
        -0.06411405,  0.09181669, -0.26921713,  0.03569013, -0.24300145,
         0.09427929,  0.18838534,  0.16128236,  0.10781345,  0.15563214,
        -0.2614793 ,  0.3105052 , -0.01142967, -0.27536133, -0.3056498 ,
         0.18365213, -0.11383317, -0.20040947,  0.28103477,  0.14767385]],
      dtype=float32)>), (None, <tf.Variable 'dense_155/bias:0' shape=(30,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)).